AllCops:
  Include:
    - metadata.rb
    - Gemfile
    - attributes/**
    - libraries/**
    - providers/**
    - recipes/**
    - resources/**
    - spec/**
  Exclude:
    - .cookbooks/**/*
    - berks-cookbooks/**/*
    - .bundle/**/*

Encoding:
  Exclude:
    - metadata.rb
    - Gemfile

NumericLiterals:
  Enabled: false

LineLength:
  Enabled: false

WordArray:
  MinSize: 3

Style/Next:
  Description: Use `next` to skip iteration instead of a condition at the end.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#no-nested-conditionals
  Enabled: true
  EnforcedStyle: always
  SupportedStyles:
  - skip_modifier_ifs
  - always
